### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by Anjaan-g** [dahsameer/nepse-api-helper#1]
I tried to run the package but it's throwing Failed to Fetch every time. Has NEPSE updated its security or am I doing something wrong?

**Comment by dahsameer** [comment]
still working as of now. some things things to consider that is probably giving you problems:

1. node version >= 18 is necessary. it uses experimental fetch api.
2. you will need to add an environment variable NODE_TLS_REJECT_UNAUTHORIZED='0' before running your program
    you could also add `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` on the top of your program to disable SSL verification.

**Comment by Anjaan-g** [comment]
Can I get your email address?




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/30/22,
02:29:53 PM

**Comment by dahsameer** [comment]
now visible in profile

**Comment by dahsameer** [comment]
Just some clarification done in the email conversation.


> The logic was derived after a detailed reverse engineering study of the [newweb.nepalstock.com](http://newweb.nepalstock.com/) website.
> 
> Nepse API is authenticated using tokens. It first receives token from this endpoint
> GET: https://newweb.nepalstock.com/api/authenticate/prove
> 
> but the token provided by this endpoint is invalid. To make the token valid, it uses a function inside WebAssembly.
> ![image](https://user-images.githubusercontent.com/42445256/178736850-12bc710f-1a6d-4ae5-9457-803e47790956.png)
> 
> 
> Inside the webassembly, there is a sequence or array of numbers. This sequence determines the dataArr. The logic for making the token valid exists inside this webassembly file as well as some part of javascript.
> 
> From my library, GetAccessToken() method will give you the valid access token.
> 
> Now if you check the network requests for getting today's price in nepse's website, you will find that it sends an ID in the request body. This ID changes everyday.
> ![image](https://user-images.githubusercontent.com/42445256/178736905-43d19491-14ae-4784-abbb-986249e17f91.png)
> 
> So along with the valid authorization token, you will need to send this one ID in the request body for most of the endpoint request.
> the GetValidBodyId() method in my library will give you that ID.
> If you don't send this ID, you will get authorization error.
> 
> I also had prepared a document which has brief logic if you want to create your own implementation here https://github.com/dahsameer/nepse-api-document
